apiVersion: apps/v1
kind: Deployment

metadata:
  name: myntra-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: myntra-app

  template:
    metadata:
      labels:
        app: myntra-app

    spec:
      containers:
        - name: myntra-app
          image: image: 511176957406.dkr.ecr.ap-south-1.amazonaws.com/b11:myntra-latest

          ports:
            - containerPort: 5000

          resources:
            requests:
              cpu: 100m
              memory: 128Mi

            limits:
              cpu: 250m
              memory: 256Mi
